(() => {
  'use strict';
  const D = window.APROVAEI_DATA;
  const KEY = 'aprovaei_simulados_v1';
  const DEFAULT = { attempts: [], answers: {}, favorites: [], review: [], inProgress: null, streak: 0, lastStudy: null };
  const state = load();

  function load(){
    try { return {...DEFAULT, ...(JSON.parse(localStorage.getItem(KEY))||{})}; }
    catch { return {...DEFAULT}; }
  }
  function save(){ localStorage.setItem(KEY, JSON.stringify(state)); }
  function qs(sel,root=document){return root.querySelector(sel)}
  function qsa(sel,root=document){return [...root.querySelectorAll(sel)]}
  function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
  function fmtDate(ts){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(ts));}
  function pct(n,d){return d?Math.round(n/d*100):0;}
  function shuffle(a){return [...a].sort(()=>Math.random()-0.5)}
  function getQ(id){return D.questions.find(q=>q.id===Number(id));}
  function chapterStats(ch){
    const ids=D.questions.filter(q=>q.chapter===ch).map(q=>q.id); const all=state.attempts.flatMap(a=>a.questions||[]).filter(x=>ids.includes(x.id));
    const unique=[]; const seen=new Set(); for(const x of all){if(!seen.has(x.id+'|'+x.attemptId)){seen.add(x.id+'|'+x.attemptId);unique.push(x)}}
    const answered=unique.length, correct=unique.filter(x=>x.correct).length, wrong=unique.filter(x=>!x.correct).length;
    return {answered,correct,wrong,percent:pct(correct,answered),total:ids.length};
  }
  function overall(){
    const rows=state.attempts.flatMap(a=>a.questions||[]); const answered=rows.length, correct=rows.filter(x=>x.correct).length;
    const scores=state.attempts.map(a=>a.percent||0);
    return {answered,correct,wrong:answered-correct,percent:pct(correct,answered),attempts:state.attempts.length,best:scores.length?Math.max(...scores):0,avg:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0};
  }
  function setActive(){
    const page=document.body.dataset.page; qsa('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.page===page));
    const menu=qs('.mobile-menu'); if(menu) qsa('.nav-link',menu).forEach(a=>a.classList.toggle('active',a.dataset.page===page));
  }
  function layout(){
    const shell=qs('#app-shell'); if(!shell) return;
    shell.innerHTML=`<aside class="sidebar"><div class="brand"><span class="brand-mark">AE</span><div><strong>APROVAEI</strong><small>Simulados</small></div></div><nav>
      ${nav('index.html','Início','home','index')} ${nav('simulados.html','Simulados','clipboard','simulados')} ${nav('desempenho.html','Desempenho','chart','desempenho')} ${nav('conteudos.html','Conteúdos','book','conteudos')} ${nav('revisao.html','Revisão','refresh','revisao')} ${nav('historico.html','Histórico','clock','historico')} ${nav('ranking.html','Ranking','trophy','ranking')}
    </nav><div class="sidebar-footer"><span class="dot"></span><div><b>Modo local</b><small>Seu progresso fica neste navegador</small></div></div></aside>
    <main class="main"><header class="topbar"><button class="icon-btn mobile-toggle" aria-label="Abrir menu">☰</button><div class="crumb">${D.exam.title} <span>•</span> ${D.exam.city}</div><div class="top-actions"><span class="local-pill">LOCAL</span></div></header><div class="page-wrap"></div></main>
    <div class="mobile-menu"><div class="mobile-menu-head"><div class="brand"><span class="brand-mark">AE</span><strong>APROVAEI</strong></div><button class="icon-btn close-menu">×</button></div><nav>${nav('index.html','Início','home','index')}${nav('simulados.html','Simulados','clipboard','simulados')}${nav('desempenho.html','Desempenho','chart','desempenho')}${nav('conteudos.html','Conteúdos','book','conteudos')}${nav('revisao.html','Revisão','refresh','revisao')}${nav('historico.html','Histórico','clock','historico')}${nav('ranking.html','Ranking','trophy','ranking')}</nav></div>`;
    setActive();
    qs('.mobile-toggle')?.addEventListener('click',()=>qs('.mobile-menu').classList.add('open'));
    qs('.close-menu')?.addEventListener('click',()=>qs('.mobile-menu').classList.remove('open'));
    qsa('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>qs('.mobile-menu').classList.remove('open')));
  }
  function nav(h,t,icon,page){return `<a class="nav-link" data-page="${page}" href="${h}"><span class="nav-ico">${iconSvg(icon)}</span><span>${t}</span></a>`}
  function iconSvg(i){const m={home:'⌂',clipboard:'▣',chart:'◒',book:'▤',refresh:'↻',clock:'◷',trophy:'♜'};return m[i]||'•'}
  function statCard(label,value,sub,cls=''){return `<div class="stat-card ${cls}"><div class="stat-label">${label}</div><div class="stat-value">${value}</div>${sub?`<div class="stat-sub">${sub}</div>`:''}</div>`}
  function empty(title,text,href,label){return `<div class="empty"><div class="empty-icon">◎</div><h3>${title}</h3><p>${text}</p>${href?`<a class="btn primary" href="${href}">${label||'Começar'}</a>`:''}</div>`}
  function init(){
    if(!qs('#app-shell')) return;
    layout();
    const page=document.body.dataset.page;
    ({index:dashboard,simulados:catalogo,desempenho:desempenho,conteudos:conteudos,revisao:revisao,historico:historico,ranking:ranking}[page]||(()=>{}))();
    if(page==='simulado') simuladoPage();
    if(page==='resultado') resultadoPage();
  }

  function dashboard(){
    const o=overall(); const last=state.attempts[0]; const bestChapter=D.chapters.map(c=>({c,s:chapterStats(c.id)})).filter(x=>x.s.answered).sort((a,b)=>b.s.percent-a.s.percent)[0];
    const weak=D.chapters.map(c=>({c,s:chapterStats(c.id)})).filter(x=>x.s.answered).sort((a,b)=>a.s.percent-b.s.percent)[0];
    qs('.page-wrap').innerHTML=`<section class="hero compact"><div><span class="eyebrow">PAINEL DE PREPARAÇÃO</span><h1>Seu próximo acerto começa aqui.</h1><p>Acompanhe sua evolução, faça simulados e transforme seus erros em revisão.</p></div><a class="btn primary xl" href="simulados.html">Fazer um simulado <span>→</span></a></section>
      <section class="stats-grid">${statCard('APROVEITAMENTO',o.percent+'%',o.answered?`${o.correct} acertos em ${o.answered} questões`:'Comece a responder','accent')}${statCard('QUESTÕES',o.answered,o.wrong?`${o.wrong} para revisar`:'Nenhuma respondida')}${statCard('SIMULADOS',o.attempts,o.attempts?`Média ${o.avg}%`:'Comece seu primeiro')}${statCard('MELHOR NOTA',o.best+'%',o.best?'Seu melhor resultado':'—')}</section>
      <div class="dashboard-grid"><section class="panel continue">${last?`<div class="section-head"><div><span class="eyebrow">ÚLTIMO RESULTADO</span><h2>Continue de onde parou</h2></div><span class="status success">Concluído</span></div><div class="continue-main"><div><strong>${esc(last.title)}</strong><p>${last.questions.length} questões • ${fmtDate(last.finishedAt)}</p></div><div class="big-score">${last.percent}%</div><a class="btn secondary" href="resultado.html?id=${last.id}">Ver resultado</a></div>`:empty('Sua jornada começa agora','Faça seu primeiro simulado para gerar dados de desempenho.','simulados.html','Ver simulados')}</section>
      <section class="panel next"><span class="eyebrow">PRÓXIMO DESAFIO</span><h2>Simulado completo</h2><p>30 questões distribuídas pelos 15 conteúdos da Educação Infantil.</p><div class="mini-meta"><span>30 questões</span><span>Intermediário</span><span>45 min</span></div><a class="btn primary" href="simulado.html?mode=simulado&count=30">Começar agora</a></section></div>
      <div class="dashboard-grid lower"><section class="panel"><div class="section-head"><div><span class="eyebrow">DIAGNÓSTICO</span><h2>Como você está indo?</h2></div><a class="text-link" href="desempenho.html">Ver tudo →</a></div>${bestChapter?`<div class="insight good"><span>✓</span><div><b>Ponto forte</b><p>${esc(bestChapter.c.name)} — ${bestChapter.s.percent}%</p></div></div>`:''}${weak?`<div class="insight warn"><span>!</span><div><b>Ponto de atenção</b><p>${esc(weak.c.name)} — ${weak.s.percent}%</p></div></div>`:''}${!bestChapter&&!weak?`<p class="muted">Responda algumas questões para liberar seu diagnóstico por conteúdo.</p>`:''}</section><section class="panel"><div class="section-head"><div><span class="eyebrow">ACESSO RÁPIDO</span><h2>Escolha seu próximo passo</h2></div></div><div class="quick-grid"><a href="revisao.html" class="quick"><b>Revisão inteligente</b><span>Questões que você errou →</span></a><a href="conteudos.html" class="quick"><b>Ver conteúdos</b><span>15 capítulos do edital →</span></a></div></section></div>`;
  }

  function catalogo(){
    const attempts=state.attempts; const cards=[1,2,3,4,5].map((n,i)=>{const title=`Simulado ${String(n).padStart(2,'0')} • Educação Infantil`; const a=attempts.find(x=>x.title===title); return {n,title,percent:a?.percent||null,diff:i<2?'Fácil':i<4?'Intermediário':'Avançado',time:i<2?30:i<4?40:50,count:30};});
    qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">BANCO DE PROVAS</span><h1>Simulados</h1><p>Escolha uma prova pronta ou monte uma sessão sob medida.</p></div><a class="btn primary" href="#builder">Montar simulado</a></div><div class="filter-row"><button class="filter active" data-filter="all">Todos</button><button class="filter" data-filter="new">Não iniciados</button><button class="filter" data-filter="done">Concluídos</button><button class="filter" data-filter="easy">Fácil</button><button class="filter" data-filter="mid">Intermediário</button><button class="filter" data-filter="hard">Avançado</button></div><div class="sim-grid" id="sim-cards">${cards.map(c=>simCard(c)).join('')}</div><section class="panel builder" id="builder"><div class="section-head"><div><span class="eyebrow">PERSONALIZE</span><h2>Monte seu simulado</h2><p>As questões são selecionadas exclusivamente do banco existente.</p></div></div><div class="builder-grid"><label>Quantidade<select id="build-count"><option>10</option><option>20</option><option selected>30</option><option>50</option></select></label><label>Modo<select id="build-mode"><option value="simulado">Cronometrado</option><option value="treino">Modo treino</option><option value="simulado-no-time">Sem tempo</option></select></label><div class="field-full"><span>Conteúdos</span><div class="chapter-checks"><label><input type="checkbox" id="all-chapters" checked> Todos</label>${D.chapters.map(c=>`<label><input type="checkbox" class="chapter-check" value="${c.id}"> ${String(c.id).padStart(2,'0')} — ${esc(c.name)}</label>`).join('')}</div></div><button class="btn primary xl" id="generate">Gerar simulado</button></div></section>`;
    qsa('.filter').forEach(b=>b.addEventListener('click',()=>{qsa('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active'); const f=b.dataset.filter;qsa('.sim-card').forEach(c=>{const ok=f==='all'||(f==='new'&&c.dataset.done==='false')||(f==='done'&&c.dataset.done==='true')||(f==='easy'&&c.dataset.diff==='Fácil')||(f==='mid'&&c.dataset.diff==='Intermediário')||(f==='hard'&&c.dataset.diff==='Avançado');c.style.display=ok?'':'none';})}));
    qs('#all-chapters')?.addEventListener('change',e=>qsa('.chapter-check').forEach(x=>x.checked=e.target.checked));
    qsa('.chapter-check').forEach(x=>x.addEventListener('change',()=>{if([...qsa('.chapter-check')].some(x=>x.checked))qs('#all-chapters').checked=false;}));
    qs('#generate')?.addEventListener('click',()=>{const count=Number(qs('#build-count').value);const mode=qs('#build-mode').value;const selected=[...qsa('.chapter-check:checked')].map(x=>Number(x.value));const ids=selected.length?D.questions.filter(q=>selected.includes(q.chapter)):D.questions;const picked=shuffle(ids).slice(0,Math.min(count,ids.length)); if(picked.length<count){alert(`Há apenas ${picked.length} questões disponíveis para essa seleção.`);return;} startNew(picked.map(q=>q.id),mode==='treino'?'treino':mode==='simulado-no-time'?'sem-tempo':'simulado',`Simulado personalizado • ${count} questões`)});
  }
  function simCard(c){const done=!!c.percent; return `<article class="sim-card" data-done="${done}" data-diff="${c.diff}"><div class="sim-top"><span class="number">0${c.n}</span><span class="difficulty">${c.diff}</span></div><h3>${c.title}</h3><p>Questões dos 15 conteúdos do edital, com correção e análise por capítulo.</p><div class="sim-meta"><span>${c.count} questões</span><span>${c.time} min</span></div><div class="sim-bottom"><span class="status ${done?'success':'neutral'}">${done?`Concluído · ${c.percent}%`:'Não iniciado'}</span><button class="btn secondary small" data-start="${c.n}">Começar</button></div></article>`}

  function startNew(ids,mode,title){const session={id:'run_'+Date.now(),title,mode,questionIds:ids,answers:{},index:0,startedAt:Date.now(),elapsed:0};state.inProgress=session;save();location.href=`simulado.html?session=${session.id}`}
  function getSession(){return state.inProgress}
  function simuladoPage(){
    let s=getSession(); if(!s){const mode=new URLSearchParams(location.search).get('mode')||'simulado';const count=Number(new URLSearchParams(location.search).get('count')||30);const ids=shuffle(D.questions).slice(0,Math.min(count,D.questions.length)).map(q=>q.id);s={id:'run_'+Date.now(),title:`Simulado • ${count} questões`,mode,questionIds:ids,answers:{},index:0,startedAt:Date.now(),elapsed:0};state.inProgress=s;save();}
    const questions=s.questionIds.map(getQ); let timer=null;
    qs('.page-wrap').innerHTML=`<div class="exam-shell"><div class="exam-head"><div><span class="eyebrow">${s.mode==='treino'?'MODO TREINO':'SIMULADO'}</span><h1>${esc(s.title)}</h1></div><div class="exam-tools"><div class="timer" id="timer">${s.mode==='treino'?'SEM CRONÔMETRO':'00:00'}</div><button class="btn ghost" id="finish">Finalizar</button></div></div><div class="exam-progress"><div><b id="counter"></b><span id="answered-count"></span></div><div class="progress"><i id="exam-bar"></i></div></div><div class="exam-grid"><aside class="question-nav"><div class="nav-title">QUESTÕES</div><div class="q-grid" id="q-grid"></div><div class="q-legend"><span><i class="dot unanswered"></i> Não respondida</span><span><i class="dot answered"></i> Respondida</span></div></aside><section class="question-panel" id="question-panel"></section></div></div>`;
    function render(){const q=questions[s.index]; const selected=s.answers[q.id]; const answered=Object.keys(s.answers).length; qs('#counter').textContent=`Questão ${s.index+1} de ${questions.length}`;qs('#answered-count').textContent=`${answered} de ${questions.length} respondidas`;qs('#exam-bar').style.width=(answered/questions.length*100)+'%';qs('#q-grid').innerHTML=questions.map((x,i)=>`<button class="qnum ${s.answers[x.id]!=null?'answered':''} ${i===s.index?'current':''}" data-i="${i}">${String(i+1).padStart(2,'0')}</button>`).join('');
      qs('#question-panel').innerHTML=`<div class="question-kicker">QUESTÃO ${String(s.index+1).padStart(2,'0')} <span>${esc(q.topic)}</span></div><h2>${esc(q.question)}</h2><div class="options">${q.options.map(o=>`<label class="option ${selected===o.label?'selected':''}" data-label="${o.label}"><input type="radio" name="answer" value="${o.label}" ${selected===o.label?'checked':''}><span class="option-letter">${o.label}</span><span>${esc(o.text)}</span></label>`).join('')}</div><div id="training-feedback"></div><div class="question-actions"><button class="btn secondary" id="prev" ${s.index===0?'disabled':''}>← Anterior</button><button class="btn primary" id="next">${s.index===questions.length-1?'Finalizar':'Próxima →'}</button></div>`;
      qsa('.option').forEach(el=>el.addEventListener('click',()=>{s.answers[q.id]=el.dataset.label; save(); render(); if(s.mode==='treino') showTrainingFeedback(q)}));
      qsa('.qnum').forEach(b=>b.addEventListener('click',()=>{s.index=Number(b.dataset.i);save();render();}));
      qs('#prev').onclick=()=>{if(s.index>0){s.index--;save();render();}};
      qs('#next').onclick=()=>{if(s.index<questions.length-1){s.index++;save();}else finishAttempt();render();};
      if(s.mode==='treino'&&selected) showTrainingFeedback(q);
    }
    function showTrainingFeedback(q){const chosen=s.answers[q.id];const correct=chosen===q.answer;qs('#training-feedback').innerHTML=`<div class="feedback ${correct?'correct':'wrong'}"><b>${correct?'✓ Resposta correta':'✕ Resposta incorreta'}</b>${!correct?`<p>Alternativa correta: <strong>${q.answer}</strong></p>`:''}<p>${esc(q.explanation)}</p></div>`}
    function tick(){if(s.mode==='treino'||s.mode==='sem-tempo'){qs('#timer').textContent='SEM CRONÔMETRO';return;}const sec=Math.floor((Date.now()-s.startedAt)/1000);s.elapsed=sec;const mm=String(Math.floor(sec/60)).padStart(2,'0'),ss=String(sec%60).padStart(2,'0');qs('#timer').textContent=`${mm}:${ss}`;}
    function finishAttempt(){const unanswered=questions.filter(q=>s.answers[q.id]==null).length;if(unanswered&& !confirm(`Você ainda possui ${unanswered} questão(ões) sem resposta. Deseja realmente finalizar?`))return;const rows=questions.map(q=>({id:q.id,answer:s.answers[q.id]||null,correct:s.answers[q.id]===q.answer}));const correct=rows.filter(r=>r.correct).length;const attempt={id:'att_'+Date.now(),title:s.title,mode:s.mode,questions:rows,percent:pct(correct,questions.length),correct,wrong:questions.length-correct-unanswered,unanswered,elapsed:s.mode==='simulado'?Math.floor((Date.now()-s.startedAt)/1000):0,startedAt:s.startedAt,finishedAt:Date.now()};state.attempts.unshift(attempt);state.inProgress=null;state.lastStudy=Date.now();save();location.href=`resultado.html?id=${attempt.id}`}
    qs('#finish').onclick=finishAttempt;render();tick();timer=setInterval(tick,1000);window.addEventListener('beforeunload',()=>{s.elapsed=Math.floor((Date.now()-s.startedAt)/1000);save()});
  }

  function resultadoPage(){const id=new URLSearchParams(location.search).get('id');const a=state.attempts.find(x=>x.id===id)||state.attempts[0];if(!a){qs('.page-wrap').innerHTML=empty('Nenhum resultado','Finalize um simulado para ver seu desempenho.','simulados.html','Ir para simulados');return;}const rows=a.questions.map(r=>({...r,q:getQ(r.id)}));qs('.page-wrap').innerHTML=`<div class="result-hero"><div><span class="eyebrow">SIMULADO CONCLUÍDO</span><h1>${esc(a.title)}</h1><p>${fmtDate(a.finishedAt)} • ${a.elapsed?formatTime(a.elapsed):'Sem cronômetro'}</p></div><a class="btn secondary" href="simulados.html">Novo simulado</a></div><section class="result-summary"><div class="score-ring" style="--p:${a.percent*3.6}deg"><div><strong>${a.percent}%</strong><span>aproveitamento</span></div></div><div class="result-stats"><div><b>✓ ${a.correct}</b><span>Acertos</span></div><div><b>✕ ${a.wrong}</b><span>Erros</span></div><div><b>— ${a.unanswered}</b><span>Não respondidas</span></div><div><b>${a.elapsed?formatTime(a.elapsed):'—'}</b><span>Tempo</span></div></div><div class="result-message">${resultMessage(a.percent)}</div></section><section class="panel"><div class="section-head"><div><span class="eyebrow">ANÁLISE POR CONTEÚDO</span><h2>Onde você foi melhor?</h2></div></div><div class="mini-bars">${resultChapterBars(rows).join('')}</div></section><section class="panel correction"><div class="section-head"><div><span class="eyebrow">CORREÇÃO</span><h2>Questões do simulado</h2><p>O gabarito e as explicações ficam disponíveis somente após a finalização.</p></div></div>${rows.map((r,i)=>correction(r,i)).join('')}</section>`;}
  function resultMessage(p){if(p>=85)return '<b>Excelente desempenho.</b> Você está construindo uma margem forte para a prova. Mantenha a consistência.';if(p>=70)return '<b>Bom desempenho.</b> Você está no caminho certo. Use os erros para ganhar pontos nas próximas tentativas.';if(p>=60)return '<b>Atenção.</b> Sua base está em construção. Priorize os conteúdos com menor desempenho antes de repetir a prova.';return '<b>Hora de revisar.</b> Use a revisão inteligente para transformar os erros deste simulado em novos acertos.'}
  function resultChapterBars(rows){const by={};rows.forEach(r=>{const c=r.q.chapter;(by[c]??=[]).push(r)});return Object.entries(by).map(([c,rs])=>{const p=pct(rs.filter(r=>r.correct).length,rs.length);return `<div class="bar-row"><span>${String(c).padStart(2,'0')} — ${esc(D.chapters[c-1].name)}</span><b>${p}%</b><div class="progress"><i style="width:${p}%"></i></div></div>`})}
  function correction(r,i){const fav=state.favorites.includes(r.id);return `<article class="correction-item ${r.correct?'is-correct':'is-wrong'}"><div class="correction-head"><span>Questão ${String(i+1).padStart(2,'0')}</span><b>${r.correct?'✓ CORRETA':'✕ ERRADA'}</b><button class="star ${fav?'on':''}" data-fav="${r.id}">★</button></div><h3>${esc(r.q.question)}</h3><div class="answer-box"><span>Sua resposta</span><strong>${r.answer||'Não respondida'}${r.answer?')':''}</strong></div>${!r.correct?`<div class="answer-box correct-box"><span>Alternativa correta</span><strong>${r.q.answer})</strong></div>`:''}<div class="explanation"><b>Explicação</b><p>${esc(r.q.explanation)}</p></div><button class="text-link review-btn" data-review="${r.id}">${state.review.includes(r.id)?'✓ Na revisão':'↻ Marcar para revisar'}</button></article>`}

  function desempenho(){const o=overall();const chapters=D.chapters.map(c=>({c,s:chapterStats(c.id)}));const attempted=chapters.filter(x=>x.s.answered);const best=[...attempted].sort((a,b)=>b.s.percent-a.s.percent)[0],weak=[...attempted].sort((a,b)=>a.s.percent-b.s.percent)[0];qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">SEU DIAGNÓSTICO</span><h1>Desempenho</h1><p>Uma visão geral do que seus dados mostram até agora.</p></div></div><section class="stats-grid">${statCard('APROVEITAMENTO',o.percent+'%',`${o.correct} acertos`,'accent')}${statCard('RESPONDIDAS',o.answered,`${o.wrong} erros`)}${statCard('MELHOR NOTA',o.best+'%',o.attempts?`${o.attempts} simulados`:'—')}${statCard('MÉDIA',o.avg+'%',o.attempts?'dos simulados':'—')}</section><div class="dashboard-grid"><section class="panel"><div class="section-head"><div><span class="eyebrow">EVOLUÇÃO</span><h2>Sua trajetória</h2></div></div>${evolution()}</section><section class="panel"><span class="eyebrow">DIAGNÓSTICO</span>${best?`<div class="insight good"><span>✓</span><div><b>Seu ponto forte</b><p>${esc(best.c.name)} — ${best.s.percent}%</p></div></div>`:''}${weak?`<div class="insight warn"><span>!</span><div><b>Priorize este conteúdo</b><p>${esc(weak.c.name)} — ${weak.s.percent}%</p></div></div>`:''}${!attempted.length?'<p class="muted">Ainda não há dados suficientes.</p>':''}</section></div><section class="panel"><div class="section-head"><div><span class="eyebrow">MAPA DE DESEMPENHO</span><h2>15 conteúdos</h2></div><a class="text-link" href="conteudos.html">Detalhar →</a></div><div class="performance-list">${chapters.map(({c,s})=>performanceRow(c,s)).join('')}</div></section>`}
  function evolution(){if(!state.attempts.length)return '<div class="empty compact-empty"><h3>Faça seu primeiro simulado</h3><p>Seu gráfico de evolução aparecerá aqui.</p></div>';const data=[...state.attempts].reverse();const max=100;return `<div class="evo-chart"><div class="y-axis"><span>100%</span><span>50%</span><span>0%</span></div><div class="bars">${data.map((a,i)=>`<div class="evo-col"><div class="evo-bar" style="height:${Math.max(4,a.percent/max*100)}%"><span>${a.percent}%</span></div><small>${i+1}</small></div>`).join('')}</div></div><p class="evo-caption">${data.length>1?`Seu desempenho variou ${Math.abs(data[data.length-1].percent-data[0].percent)} pontos desde o primeiro simulado.`:'O primeiro resultado foi registrado. Continue para construir sua curva de evolução.'}</p>`}
  function performanceRow(c,s){const status=s.answered===0?'Sem dados':s.percent>=80?'Domínio alto':s.percent>=60?'Atenção':'Precisa melhorar';const cls=s.answered===0?'neutral':s.percent>=80?'success':s.percent>=60?'warning':'danger';return `<div class="perf-row"><div class="perf-name"><b>${String(c.id).padStart(2,'0')}</b><span>${esc(c.name)}</span></div><div class="perf-main"><div class="progress"><i class="${cls}" style="width:${s.percent}%"></i></div><span>${s.percent}%</span></div><span class="status ${cls}">${status}</span></div>`}

  function conteudos(){qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">15 CAPÍTULOS</span><h1>Desempenho por conteúdo</h1><p>Identifique rapidamente seus pontos fortes e os conteúdos que merecem revisão.</p></div></div><div class="content-grid">${D.chapters.map(c=>{const s=chapterStats(c.id);return `<article class="content-card"><div class="content-number">${String(c.id).padStart(2,'0')}</div><div class="content-body"><h3>${esc(c.name)}</h3><div class="content-score"><strong>${s.percent}%</strong><span>${s.answered?`${s.answered} questões respondidas`:'Ainda não estudado'}</span></div><div class="progress"><i style="width:${s.percent}%"></i></div><div class="content-meta"><span>${s.correct} acertos</span><span>${s.wrong} erros</span><a href="revisao.html?chapter=${c.id}">Revisar →</a></div></div></article>`}).join('')}</div>`}

  function revisao(){const wrongIds=[...new Set(state.attempts.flatMap(a=>a.questions.filter(r=>!r.correct).map(r=>r.id)))];const fav=state.favorites;const marked=state.review;const weak=D.chapters.map(c=>({c,s:chapterStats(c.id)})).filter(x=>x.s.answered).sort((a,b)=>a.s.percent-b.s.percent).slice(0,3);qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">REVISÃO INTELIGENTE</span><h1>Revisão</h1><p>Volte exatamente onde você mais pode ganhar pontos.</p></div>${wrongIds.length?`<button class="btn primary" id="start-wrong">Revisar erros (${wrongIds.length})</button>`:''}</div><div class="review-grid"><section class="panel"><div class="section-head"><div><span class="eyebrow">🔥 PRIORIDADE</span><h2>Questões que você errou</h2></div></div>${wrongIds.length?`<div class="review-list">${wrongIds.slice(0,8).map(id=>reviewQuestion(id)).join('')}</div>`:empty('Nenhum erro ainda','Faça um simulado e seus erros aparecerão aqui.')}</section><section class="panel"><div class="section-head"><div><span class="eyebrow">⭐ SALVAS</span><h2>Favoritas</h2></div></div>${fav.length?fav.slice(0,8).map(id=>reviewQuestion(id)).join(''):empty('Sua coleção está vazia','Use a estrela na correção para guardar questões importantes.')}</section></div><section class="panel"><div class="section-head"><div><span class="eyebrow">📚 PONTOS FRACOS</span><h2>Conteúdos para priorizar</h2></div></div>${weak.length?`<div class="weak-grid">${weak.map(x=>`<a class="weak-card" href="conteudos.html"><b>${esc(x.c.name)}</b><span>${x.s.percent}% de aproveitamento</span><small>${x.s.answered} respondidas · ${x.s.wrong} erros</small></a>`).join('')}</div>`:'<p class="muted">Responda questões de diferentes capítulos para criar recomendações.</p>'}</section>`;
    qs('#start-wrong')?.addEventListener('click',()=>startNew(wrongIds,'treino','Revisão inteligente • seus erros'));
    qsa('[data-review]').forEach(b=>b.addEventListener('click',()=>{toggleReview(Number(b.dataset.review));revisao();}));
  }
  function reviewQuestion(id){const q=getQ(id);return `<div class="review-q"><div><span class="qtag">${String(q.chapter).padStart(2,'0')}</span><b>${esc(q.question)}</b></div><button class="star ${state.favorites.includes(id)?'on':''}" data-fav="${id}">★</button></div>`}
  function toggleReview(id){const i=state.review.indexOf(id);if(i>=0)state.review.splice(i,1);else state.review.push(id);save()}
  function toggleFav(id){const i=state.favorites.indexOf(id);if(i>=0)state.favorites.splice(i,1);else state.favorites.push(id);save()}

  function historico(){qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">SEU CAMINHO</span><h1>Histórico</h1><p>Todos os simulados concluídos neste navegador.</p></div></div><section class="panel history-panel">${state.attempts.length?state.attempts.map((a,i)=>`<div class="history-row"><div class="history-num">${String(state.attempts.length-i).padStart(2,'0')}</div><div class="history-info"><b>${esc(a.title)}</b><span>${fmtDate(a.finishedAt)} • ${a.questions.length} questões • ${a.elapsed?formatTime(a.elapsed):'sem tempo'}</span></div><div class="history-score ${a.percent>=80?'high':a.percent>=60?'mid':'low'}">${a.percent}%</div><a class="btn secondary small" href="resultado.html?id=${a.id}">Ver resultado</a></div>`).join(''):empty('Ainda não há histórico','Conclua um simulado para registrar seu resultado.','simulados.html','Fazer primeiro simulado')}</section>`}
  function ranking(){qs('.page-wrap').innerHTML=`<div class="page-title"><div><span class="eyebrow">RECURSO FUTURO</span><h1>Ranking</h1><p>Uma área preparada para futura integração com contas e backend.</p></div></div><section class="ranking-placeholder"><div class="rank-icon">♜</div><h2>Ranking online em breve</h2><p>Sem backend e login, o APROVAEI mantém seu progresso apenas no navegador. Quando houver infraestrutura online, esta tela poderá comparar desempenho por turma, cidade ou simulado.</p><div class="future-list"><span>✓ Estrutura visual pronta</span><span>✓ Espaço para integração de API</span><span>✓ Sem dados fictícios apresentados como reais</span></div></section>`}

  function formatTime(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}h ${String(m).padStart(2,'0')}min`: `${m}min ${String(s).padStart(2,'0')}s`}
  function resultOf(id){return state.attempts.find(a=>a.id===id)}
  // Global delegated interactions
  document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){toggleFav(Number(fav.dataset.fav));fav.classList.toggle('on',state.favorites.includes(Number(fav.dataset.fav)));}const start=e.target.closest('[data-start]');if(start){const n=Number(start.dataset.start);const ids=shuffle(D.questions).slice(0,30).map(q=>q.id);startNew(ids,'simulado',`Simulado ${String(n).padStart(2,'0')} • Educação Infantil`);}});
  window.APROVAEI={state,save,getQ,startNew,toggleFav,toggleReview,overall,chapterStats,resultOf};
  init();
})();
